- name: include OS defaults (RedHat/CentOS)
  include_vars: RedHat.yaml
  when:
    - ansible_system == "Linux"
    - ansible_os_family == "RedHat"

- name: include OS defaults (Debian/Ubuntu)
  include_vars: Debian.yaml
  when:
    - ansible_system == "Linux"
    - ansible_os_family == "Debian"

- name: include OS defaults (SmartOS)
  include_vars: SmartOS.yaml
  when:
    - ansible_system == "SunOS"
    - ansible_os_family == "Solaris"
    - ansible_distribution == "SmartOS"

- name: Copy the nginx repo (RedHat / CentOS)
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo
  when: 
    - (nginx_install_repo is defined and nginx_install_repo|lower == "true")
    - ansible_system == "Linux"
    - ansible_os_family == "RedHat"

- name: Copy the nginx repo (Debian / Ubuntu)
  template: src=nginx.list.j2 dest=/etc/apt/sources.list.d/nginx.list
  when:
    - (nginx_install_repo is defined and nginx_install_repo|lower == "true")
    - ansible_system == "Linux"
    - ansible_os_family == "Debian"

- name: Install the nginx package
  package: name=nginx state=present

- name: Install the certbot packages
  apt: name=certbot state=present update_cache=yes default_release=jessie-backports
  environment: '{{ env }}'
  when:
    - (nginx_use_letsencrypt is defined and nginx_use_letsencrypt|lower == "true")
    - ansible_system == "Linux"
    - ansible_os_family == "Debian"

- name: Install the certbot packages
  yum: name=certbot state=present
  when:
    - (nginx_use_letsencrypt is defined and nginx_use_letsencrypt|lower == "true")
    - ansible_system == "Linux"
    - ansible_os_family == "RedHat"

- name: Create the directories for site specific configurations and ssl keys (Linux)
  file: path={{ nginx_config_dir }}/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - "conf.d"
    - "sites-available"
    - "sites-enabled"
    - "ssl"

- name: Check if main nginx.conf exists
  stat: path={{ nginx_config_dir }}/nginx.conf
  register: nginx_conf_exists

- name: Create the nginx configuration file
  template: src=nginx.conf.j2 dest={{ nginx_config_dir }}/nginx.conf
  when: (nginx_create_nginx_conf is defined and nginx_create_nginx_conf|lower == "true") or nginx_conf_exists is not defined
  notify:
   - restart nginx

- name: create directory /srv/www/letsencrypt/
  file: path=/srv/www/letsencrypt/{{item.file_name}} state=directory
  with_items:
    - "{{ nginx_sites }}"
  when:
    - ansible_system == "Linux"
    - nginx_use_letsencrypt is defined
    - nginx_use_letsencrypt|lower == "true"

- name: Delete the links to delete site configurations for letsencrypt
  file: path={{ nginx_config_dir }}/sites-enabled/{{ item.file_name }} state=absent src={{ nginx_config_dir }}/sites-available/{{ item.file_name }}
  with_items: "{{nginx_sites}}"
  when:
    - ansible_system == "Linux"
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.supplier == "letsencrypt"
    - nginx_manage_letsencrypt

- name: Create the configurations for sites (Linux)
  template: src=site_letsencrypt.j2 dest={{ nginx_config_dir }}/sites-available/{{ item.file_name }}
  with_items:
    - "{{nginx_sites}}"
  when:
    - ansible_system == "Linux"
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.supplier == "letsencrypt"
    - nginx_manage_letsencrypt

- name: Create the links to enable site configurations for letsencrypt (Linux)
  file: path={{ nginx_config_dir }}/sites-enabled/{{ item.file_name }} state=link src={{ nginx_config_dir }}/sites-available/{{ item.file_name }}
  with_items:
    - "{{nginx_sites}}"
  when:
    - ansible_system == "Linux"
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.supplier == "letsencrypt"
    - nginx_manage_letsencrypt

- name: reload nginx (Linux)
  service: name=nginx state=reloaded
  with_items:
    - "{{nginx_sites}}"
  when:
    - ansible_system == "Linux"
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.supplier == "letsencrypt"

- name: configure certbot webroot plugin (Linux)
  command: certbot certonly -n --expand --webroot -w "/srv/www/letsencrypt/{{item.file_name}}" -d "{{item.ssl.domains|join(',')}}" --cert-name "{{ item.file_name }}"
  with_items:
    - "{{nginx_sites}}"
  when:
    - ansible_system == "Linux"
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.supplier == "letsencrypt"
    - nginx_manage_letsencrypt

- name: Copy SSL keys
  copy: src={{ item.ssl.local_keystore_dir }}/{{item.ssl.key }} dest={{ nginx_ssl_dir }}/{{ item.ssl.key }}  owner={{ nginx_uid }} group={{ nginx_gid }} mode=400 backup=no
  with_items:
    - "{{nginx_sites }}"
  when:
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.key is defined
    - item.ssl.key != None
    - item.ssl.supplier == "local"

- name: Copy SSL certificates
  copy: src={{ item.ssl.local_keystore_dir }}/{{item.ssl.certificate }} dest={{ nginx_ssl_dir }}/{{ item.ssl.certificate }}  owner={{ nginx_uid }} group={{ nginx_gid }} mode=644 backup=no
  with_items:
    - "{{nginx_sites }}"
  when:
    - item.ssl is defined
    - item.ssl != None
    - item.ssl.certificate is defined
    - item.ssl.certificate != None
    - item.ssl.supplier == "local"

- name: Create Mail Proxy configuration
  template: src=mail.conf.j2 dest={{ nginx_config_dir }}/mail.conf
  when:
    - nginx_mail_params is defined
    - nginx_mail_servers is defined
  notify:
    - reload nginx

- name: Create the configurations for sites
  template: src=site.j2 dest={{ nginx_config_dir }}/sites-available/{{ item.file_name }}
  with_items: "{{nginx_sites}}"

- name: Create the configuration for upstreams
  template: src=upstream.j2 dest={{ nginx_config_dir }}/conf.d/upstream-{{ item.name }}.conf
  with_items: "{{nginx_upstreams}}"

- name: Create the links to enable site configurations
  file: path={{ nginx_config_dir }}/sites-enabled/{{ item.file_name }} state=link src={{ nginx_config_dir }}/sites-available/{{ item.file_name }}
  with_items: "{{nginx_sites}}"
  notify:
   - reload nginx

- name: start the nginx service
  service: name=nginx state=started enabled=yes

- name: Add cronjob for letsencrypt bot (Linux)
  cron: name="Update letsencrypt certs" minute="15" hour="3" job="/usr/bin/certbot renew --quiet --renew-hook \"/usr/sbin/service nginx reload\""
  when:
    - ansible_system == "Linux"
    - nginx_use_letsencrypt is defined
    - nginx_use_letsencrypt|lower == "true"
    - nginx_manage_letsencrypt
